apiVersion: v1
kind: Namespace
metadata:
  name: apaf
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: v1.29

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: workspace
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt"
    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-claim
  namespace: apaf
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apaf-deployment
  namespace: apaf
  labels:
    app: apaf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apaf
  template:
    metadata:
      labels:
        app: apaf
    spec:
      volumes:
      - name: workspace-storage
        persistentVolumeClaim:
          claimName: workspace-claim
      containers:
      - name: apaf
        image: 192.168.2.218:5000/apaf:1.3
        ports:
        - containerPort: 9080
          name: apaf-web-port
        volumeMounts:
        - mountPath: "/opt/workspace"
          name: workspace-storage
        env:
        - name: WORKSPACE_LOC
          value: "/opt/workspace"

---
apiVersion: v1
kind: Service
metadata:
   name: apaf-lb
   namespace: apaf
spec:
   type: ClusterIP
   selector:
      app: apaf
   ports:
      - protocol: TCP
        port: 80
        targetPort: 9080
   externalIPs:
     - 192.168.2.218
     
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apaf-ingress
  namespace: apaf
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: apaf-lb
            port:
              number: 80
