apiVersion: v1
kind: ServiceAccount
metadata:
  name: apaf-admin
  namespace: apaf
---
apiVersion: v1
kind: Secret
metadata:
  name: apaf-secret
  namespace: apaf
  annotations:
    kubernetes.io/service-account.name: apaf-admin
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: apaf
  name: apaf-manager
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "watch", "list","post","put","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-apaf
  namespace: apaf
subjects:
- kind: ServiceAccount
  name: apaf-admin
  namespace: apaf
roleRef:
  kind: Role
  name: apaf-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: apaf
  name: apaf-manager-cr
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manage-apaf-crb
subjects:
- kind: ServiceAccount
  name: apaf-admin
  namespace: apaf
roleRef:
  kind: ClusterRole
  name: apaf-manager-cr
  apiGroup: rbac.authorization.k8s.io
